name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: pratik2374
          outputs: dist/github-contribution-grid-snake.svg

      # Step 3: Deploy the snake to the output branch
      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
